# Generated by Django 4.1.3 on 2022-12-19 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeId', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('genero', models.TextField(verbose_name='genero')),
                ('formatoEmision', models.CharField(max_length=50, verbose_name='formato Emisión')),
                ('numEpisodios', models.PositiveIntegerField(null=True, verbose_name='Número de Episodios')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.PositiveIntegerField(verbose_name='Id del usuario')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('animeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.anime')),
            ],
            options={
                'ordering': ('idUsuario', 'animeId'),
            },
        ),
    ]
